FROM alpine:latest
RUN apk update && apk upgrade && apk add bash
RUN adduser -D -u 1001 -g 'www' www
RUN apk add nginx
RUN mkdir /app
RUN chown -R www:www /run && \
		chown -R www:www /run/nginx && \
		chown -R www:www /app && \
		chown -R www:www /var && \
		chown -R www:www /var/run && \
		chown -R www:www /etc/nginx
COPY /app /app
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8000
USER 1001
CMD ["nginx", "-c", "/etc/nginx/nginx.conf"]
