apiVersion: v1 
kind: Pod
metadata:
    name: pepehtml-v2
    labels: 
        homework: '1'
spec:
    containers:
        - image: yadwig/pepehtml
          name: pepehtml
          volumeMounts:
          - mountPath: /app
            name: app
          ports:
          - containerPort: 8000
            protocol: TCP
    initContainers:
        - image: busybox:latest
          name: pepehtml-init
          command: ['sh', '-c', "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
          volumeMounts:
            - name: app
              mountPath: /app
    volumes:
        - name: app
          emptyDir: {}